services:
  - type: web
    name: scrnk-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install chromium
    startCommand: |
      playwright install chromium && uvicorn Backend.app:app --host 0.0.0.0 --port 8000
